export const CORE_UI_EMOJI_REVISION = 'CENAR-UI-ICONS-20261002';
// Original Cenar badge treatment; Lucide glyphs retain their ISC attribution.
// Product brands use their verified brand assets, separate from this UI pack.
const definition = [
  ['check', 'BadgeCheck', ['status_check','order_created','order_complete','payment_success','card_success','cenar_verified','cenar_partner_ok','icon_green']],
  ['cross', 'X', ['status_cross','order_cancel','payment_refund','music_disconnect','icon_red']],
  ['alert', 'TriangleAlert', ['status_warn','panel_complaint','admin_order_week1','admin_order_week2']],
  ['info', 'Info', ['status_info','partner_rules','partner_guide']],
  ['loading', 'LoaderCircle', ['status_loading','order_processing','order_pending','otp_loading','cenar_cooldown']],
  ['cart', 'ShoppingCart', ['panel_order','icon_cart']],
  ['package', 'Package', ['order_product']],
  ['ticket', 'Ticket', ['ticket_open','icon_ticket']],
  ['shield', 'ShieldCheck', ['panel_warranty','ticket_claim','warranty_shield','verify_shield']],
  ['user', 'UserRound', ['ticket_user','customer_patron']],
  ['staff', 'Headset', ['panel_support','ticket_staff','cenar_support','cenar_staff']],
  ['wallet', 'Wallet', ['payment_money','icon_wallet','cenar_wallet']],
  ['card', 'CreditCard', ['payment_payos']],
  ['qr', 'QrCode', ['payment_qr']],
  ['bank', 'Landmark', ['payment_vietqr']],
  ['clock', 'Clock3', ['icon_clock','icon_duration','icon_expire']],
  ['calendar', 'CalendarDays', ['icon_calendar','warranty_purchase','warranty_expiry']],
  ['tag', 'Tag', ['icon_price','icon_tag','cenar_price','promo_discount']],
  ['store', 'Store', ['stock_header','icon_store']],
  ['gift', 'Gift', ['icon_gift','promo_legend']],
  ['settings', 'Settings2', ['icon_settings']],
  ['star', 'Star', ['icon_star']],
  ['file', 'FileText', ['icon_doc','icon_history','transcript_web','recovery_backup']],
  ['receipt', 'ReceiptText', ['order_id','icon_id']],
  ['link', 'Link', ['icon_link']],
  ['chart', 'BarChart3', ['icon_chart']],
  ['crown', 'Crown', ['icon_crown','cenar_admin','admin_order_center']],
  ['gem', 'Gem', ['icon_gem','ctv_crystal','cenar_ctv']],
  ['heart', 'Heart', ['icon_heart','icon_heart_purple']],
  ['search', 'Search', ['icon_search']],
  ['right', 'ArrowRight', ['icon_next']],
  ['left', 'ArrowLeft', ['icon_prev']],
  ['play', 'Play', ['music_play']],
  ['pause', 'Pause', ['music_pause']],
  ['skip', 'SkipForward', ['music_skip']],
  ['stop', 'Square', ['music_stop']],
  ['repeat', 'Repeat2', ['music_loop','icon_cycle']],
  ['shuffle', 'Shuffle', ['music_shuffle']],
  ['volume', 'Volume2', ['music_volume']],
  ['music', 'AudioLines', ['music_wave','music_now','music_queue']],
  ['refresh', 'RefreshCw', ['music_refresh','music_add','recovery_restore']],
  ['announce', 'Megaphone', ['icon_announce','cenar_announce']],
  ['trophy', 'Trophy', ['icon_trophy','icon_gold','icon_silver','icon_bronze']],
  ['book', 'BookOpen', ['icon_book']],
  ['folder', 'FolderOpen', ['icon_folder','icon_empty']],
  ['trash', 'Trash2', ['icon_trash']],
  ['lock', 'LockKeyhole', ['ticket_close','icon_block']],
  ['rocket', 'Rocket', ['icon_fire','admin_order_priority']],
  ['spark', 'Sparkles', ['icon_sparkle','icon_tip']],
  ['edit', 'PencilLine', ['panel_edit','icon_edit']],
  ['world', 'Globe', ['icon_web','icon_location']],
  ['key', 'KeyRound', ['icon_key','icon_unlock']],
  ['group', 'UsersRound', ['icon_group','panel_partnership','cenar_partner']],
  ['home', 'Home', ['icon_home']],
  ['target', 'Target', ['icon_target']],
  ['brain', 'Brain', ['icon_brain']],
  ['list', 'ListChecks', ['icon_clipboard','order_queue']],
];
export const CORE_UI_EMOJI_ASSETS = Object.freeze(definition.map(([key,glyph,slots]) => Object.freeze({
  key, glyph, name:`cenar_ui26_${key}`, fileName:`cenar_ui26_${key}.png`, slots:Object.freeze(slots),
})));
export const CORE_UI_EMOJI_SLOTS = Object.freeze(Object.fromEntries(CORE_UI_EMOJI_ASSETS.flatMap(asset => asset.slots.map(slot => [slot,asset.name]))));
